version: "3.9"
services:
  lab-nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    privileged: true
    ports:
      - "111:111/tcp"
      - "111:111/udp"
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "32765:32765/tcp"
      - "32765:32765/udp"
      - "32767:32767/tcp"
      - "32767:32767/udp"
    environment:
      - SHARED_DIRECTORY=/nfs-share
      - NFS_EXPORT_0=/nfs-share *(rw,sync,no_subtree_check,no_root_squash)
    volumes:
      - ./nfs-share:/nfs-share   # Carpeta local persistente (se crea si no existe)
    restart: unless-stopped
    networks:
      ipvlan_lab:
        ipv4_address: 192.168.X.X   # Cambiar por una IP libre de tu LAN
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
networks:
  ipvlan_lab:
    external: true