version: '3.8'
services:
  glpi:
    image: alamazon/glpi:10-0-19
    container_name: glpi
    restart: unless-stopped
    networks:
      glpi_net:
        ipv4_address: 192.168.88.129
    ports:
      - "8090:80"   # Acceso web a GLPI
    volumes:
      - "/NPATHPERSISTENTEENTUDISPOSITIVO/Persistentes/GLPI:/var/www/html/glpi"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      MYSQL_HOST: db
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi_pass  # Cambiar esta contraseña por una más fuerte
  glpi-db:
    image: mariadb:10.11
    container_name: glpi-db
    restart: unless-stopped
    networks:
      glpi_net:
        ipv4_address: 192.168.88.128   # Otra IP en tu misma red
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi_pass
    volumes:
      - "/PATHPERSISTENTEENTUDISPOSITIVO/Persistentes/GLPI-db:/var/lib/mysql"
networks:
  glpi_net:
    external: true
## Para desplegar este compose
## sudo docker-compose -f deploy-glpi.yml up -d
