version: "3.9"
services:
  gns3:
    image: alamazon/noz-gns3-server:v01
    container_name: gns3-noz
    networks:
      gns3-net:
        ipv4_address: 192.168.88.239 # Aqui va una direccion valida de tu LAN
    environment:
      BRIDGE_ADDRESS: 172.21.1.1/24
    ports:
      - "3080:3080"        # Web UI / API
      - "5000-5100:5000-5100" # Rango para dynamips/qemu/udp
    volumes:
      #- ./gns3_data:/data
      #- /var/run/docker.sock:/var/run/docker.sock # Para usar contenedores docker dentro de GNS3
    deploy:
      resources:
        limits:
          cpus: "1"  # Cantidad de CPUs asignado
          memory: 3g # Cantidad de Memoria Ram Asignada
    restart: unless-stopped
    privileged: true  # Necesario para QEMU y dynamips
networks:
  agent_network:
    driver: bridge
  gns3-net:
    external: true
## Para desplegar este compose
## sudo docker-compose -f deploy-gns3-server.yml up -d